### ISSUE TITLE
Please provide samples in data folder

### ISSUE THREAD

**Issue by bekerov** [jennykang/RNNSearch#1]
Hello. Please provide samples (train.rawcode.txt, valid.rawcode.txt) which located in  `data` folder.
Thanks

**Comment by jennykang** [comment]
Hi. They are just tokens of Java methods. Each line represents a Java method.
For example:
public RGBColor toGreyScale ( ) { return new RGBColor ( 0.30 * getRed ( ) + 0.59 * getGreen ( ) + 0.11 * getBlue ( ) ) ; }
public void add ( int index , E element ) { insertElementAt ( element , index ) ; }
